name: Publish plugin to the store

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm ci --ignore-scripts
      - run: npx skpm login ${{ secrets.SKPM_TOKEN }}
      - run: npm run build
      # - run: "npm run release:minor"
